@baseUrl = http://localhost:5148


POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Morteza Esmailpour",
  "email": "morteza2@example.com",
  "password": "Pass12345"
}

###

GET {{baseUrl}}/users/a0386dd5-2cec-4bc3-846a-147fa440e509

###
