@baseUrl = http://localhost:5148


POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Morteza Esmailpour",
  "email": "morteza@example.com",
  "password": "Pass12345"
}

###

GET {{baseUrl}}/users/6ec905ac-fecf-40a9-bae1-8d42991871e8

###
